import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import DashBoardWrapper from "./dashboardWrapper";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* We will need the navbar and the menu with all the pages so best to keep it in layout file */}
        <DashBoardWrapper>{children}</DashBoardWrapper>
      </body>
    </html>
  );
}
